version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
    - PYTHONUNBUFFERED=1
    - ID=api
    - STORAGE_EMULATOR_HOST=http://gcs:8001
    ports:
      - "8000:8000"
    networks:
      - custom_network

networks:
  custom_network:
    external: true
